[package]
name = "uku"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "2.34"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
